name: build
on: [push]

env:
    VERSION_PREFIX: "0.0.1"

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            dynamo:
                image: amazon/dynamodb-local
                ports: [ '8000:8000' ]

        steps:

          - uses: Brightspace/third-party-actions@actions/checkout

          - name: Setup .NET Core
            uses:  Brightspace/third-party-actions@actions/setup-dotnet
            with:
                dotnet-version: 3.1.x

          - name: dotnet test
            run: dotnet test --configuration Release --framework "netcoreapp3.1"

    pack:
        runs-on: windows-latest

        steps:

          - uses: Brightspace/third-party-actions@actions/checkout

          - name: Setup .NET Core
            uses:  Brightspace/third-party-actions@actions/setup-dotnet
            with:
                dotnet-version: 3.1.x

          - name: dotnet tool restore
            run: dotnet tool restore

          - name: Generate version properties
            run: dotnet ci-version-properties --output VersionInfo.props && cat VersionInfo.props

          - name: dotnet test
            run: dotnet pack --configuration Release
